server:
  port: 9090

spring:
  application:
    name: bookmark-service
  datasource:
    hikari:
      jdbc-url: "jdbc:h2:mem:test-db"
      username: "sa"
  jpa:
    open-in-view: false

logging:
  level:
    org:
      springframework:
        transaction:
          support: debug
        security: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'